### ISSUE TITLE
variable query returns "_count" as aggregate field instead of desired extracted field

### ISSUE THREAD

**Issue by jackskj** [grafana/falconlogscale-datasource#285] opened 2024-03-20 20:43 UTC
**What happened**:
variables query returns "_count" as aggregate field instead of desired extracted field, this is very likely caused by alphabetic order

**What you expected to happen**:
when the query in grafana variables page is using extracted field in an aggregate function, the desired extracted field should be the variable

**How to reproduce it (as minimally and precisely as possible)**:

create a variable with humi/logscale query, use an aggregate function (groupby/top) with extracted field.
the suggested varialbes will be outputs of "_count", not the extracted field.

**Screenshots**
Example Variable in Grafana using humio/FLS query 
What happened: 
![what_happened](https://github.com/grafana/falconlogscale-datasource/assets/26241163/6ae6fc60-78c3-4f01-8732-b1f02b1bfec7)
What is expected: 
![what_is_expected](https://github.com/grafana/falconlogscale-datasource/assets/26241163/fc05b2d1-a94c-4776-99f5-1fd94140ea4c)

**Environment**:
- Grafana version: 10
- Plugin version: 1.5

**Comment by RandGH** [comment] 2024-03-21 18:44
Not sure if that's really a bug or not but if you want to prevent the problem you can either drop _count (by adding |drop("_count") to the query) or prevent top from counting in the first place by adding function=[] to it (-> top(hostname, function=[]).
Cant verify the code atm but should be close enough:)

**Comment by aangelisc** [comment] 2024-03-22 17:37
Thank you for the report @jackskj. As @RandGH says, this is not a bug and is by design. The correct solution is to drop the fields you don't need in the query directly. I'm going to close this but feel free to re-open/respond if there's more information you'd like to add 😊

**Closed by aangelisc** 2024-03-22 17:37 UTC
Labels: type/bug, datasource/Falcon LogScale

**Comment by jackskj** [comment] 2024-03-22 19:32
thank you, sounds good, i can also see this come as an issue when using grafana table panel, 
without renaming any fields , aggregate field often appears as last column, while _count appears first. 
users would generally expect it to be the other way around 
![Screenshot 2024-03-22 at 3 30 15 PM](https://github.com/grafana/falconlogscale-datasource/assets/26241163/b9cbfea9-6b31-4592-ba78-5429cf68471d)

**Comment by RandGH** [comment] 2024-03-25 14:36
Calling Logscale from Grafana is just an add on option, so no special provisioning is being made I think.
You need to use Logscale functions to organize your data - in this case a |select([stage,_count])
